apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tsmc-ntu-g4

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: frontend
  app.kubernetes.io/name: frontend

images:
- name: asia-east1-docker.pkg.dev/tsmc-ntu-g4/app-images/frontend
  newTag: "95c7005"

configMapGenerator:
  - name: frontend-env
    envs:
      - frontend.env

generatorOptions:
  disableNameSuffixHash: true