apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-east1-docker.pkg.dev/tsmc-ntu-g4/app-images/backend
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-env 
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
