apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tsmc-ntu-g4

resources:
- deployment.yaml
- service.yaml
- hpa.yaml

commonLabels:
  app: backend
  app.kubernetes.io/name: backend

images:
- name: asia-east1-docker.pkg.dev/tsmc-ntu-g4/app-images/backend
  newTag: "2ba31ca"

configMapGenerator:
  - name: backend-env
    envs:
      - backend.env

generatorOptions:
  disableNameSuffixHash: true