apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TSMC-NTU-G4/app-configs.git
    targetRevision: HEAD
    path: monitoring
    helm:
      valueFiles:
        - values.yaml
      chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 45.7.1
  destination:
    server: https://kubernetes.default.svc
    namespace: tsmc-ntu-g4
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
