apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-sm
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: web
    path: /metrics
    interval: 10s