apiVersion: batch/v1
kind: CronJob
metadata:
  name: autoclose-alerts
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-autoclose
              image: curlimages/curl:latest
              args:
                - -X
                - DELETE
                - http://backend:8000/api/earthquake/alerts/autoclose
          restartPolicy: OnFailure
