apiVersion: batch/v1
kind: CronJob
metadata:
  name: autoclose-alerts
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: curl-autoclose
              image: curlimages/curl:latest
              args:
                - -X
                - DELETE
                - http://backend:8000/api/earthquake/alerts/autoclose
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"
          restartPolicy: Never
