
apiVersion: batch/v1
kind: CronJob
metadata:
  name: earthquake-generator-debug
spec:
  concurrencyPolicy: "Forbid"
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
          - name: earthquake-generator-debug
            image: curlimages/curl:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "🌍 Debug: CronJob started at $(date)"
                echo "📍 Backend URL: ${BACKEND_URL}"
                echo "🕒 Current time: $(TZ='Asia/Taipei' date '+%Y-%m-%d %H:%M:%S %Z')"
                echo "✅ Debug task completed successfully"
            env:
            - name: BACKEND_URL
              value: "http://backend:8000/api/earthquake/"
            resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"