apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-alerts
  template:
    metadata:
      labels:
        app: realtime-alerts
    spec:
      containers:
        - name: curl-realtime
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                curl -s http://backend:8000/api/earthquake/realtime;
                sleep 10;
              done
