apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tsmc-ntu-g4

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: redis
  app.kubernetes.io/name: redis
